### ISSUE TITLE
blank edit forms fields

### ISSUE THREAD

**Issue by WitekS** [massiws/lara-bulma#1]
When editing fields, fields should be pre-filled with values for editing, an empty form always appears here. Perhaps in the partial view 
`@include('components.form.text', [
        'field' => 'last_name' | 'object.name',
        'label' => __(file.key) (default: __("general.$field"))
        'required' => 'required' (default: '')
        'icon' => 'envelop' (default: no icon displayed),
        'readonly' (default: none)
    ]),` 
an option should be added with passing value values

**Comment by massiws** [comment]
@WitekS,
sorry, there was a bug in the partial view: it has been fixed in the last commit.
Can you try again and send me feedback?

Thank you.

**Comment by WitekS** [comment]
I solved this by adding value in `components.form.text`
`value="{{ !empty($value) && empty(old($field)) ?  $value : old($field)}}"`
and in the call, e.g.
`@include('components.form.text', ['field' => 'name', 'icon' => 'user', 'label' => 'general.name', 'value'=> $user->name])`

**Comment by massiws** [comment]
Yes, your solution works as well.

I used LaravelCollective package to generate input fields, and LaravelCollective has an `old()` function in `vendor/laravelcollective/html/src/FormBuilder.php` that is different from the `old()` function in Laravel.

Calling `old($field)` outside of LaravelCollective context don't get the required values.

Thank you for reporting this.
